### ISSUE TITLE
[Question] How to use Metis partitioning in ClusterData

### ISSUE THREAD

**Issue by shaanchandra** [rusty1s/pytorch_geometric#1043]
## ❓ Questions & Help

Hello,

Thank you for the work on the library! Really appreciate it.

I wanted to use Metis as the partitioning function in ClusterData instead of random partitioning. I see that pytorch_sparse recently added this feature. However, I do not see any option to do so. The code for ClusterData also does not support this (from what I see in the source code). I have independently installed this library and also the Metis software following the instructions.

Can the developers shed some light on how I can go about doing this? Do I need to install pytorch-sparse differently to use it? 

Thanks!

**Comment by rusty1s** [comment]
ClusterData uses metis for partioning, it does not do random clustering. If this works for you, everything is fine:)

**Comment by shaanchandra** [comment]
Hi @rusty1s ,
Thanks for the prompt response!
A quick follow up:

Just to be clear, it uses Metis even without installing Metis independently? 

I am asking this as I ran the test file `cluster_gcn.py` with GCNConv and SAGEConv on the reddit dataset and the results were quite low than expected (with the same parameters as mentioned in the cluster-GCN paper). And the paper has experiments that show that random partitioning performs worse than clustering using Metis.

Or could it be because the GCNConv in this library is the vanilla GCN (original paper by Kipf and Welling) and does not have the tweaks and tricks that authors of cluster-GCN made to it?

**Comment by rusty1s** [comment]
If you install `torch-sparse` from source, you need to also have metis installed (see README of `torch-sparse`). If you simply use our binaries, then this functionality is already included. Generally speaking, `ClusterGCN` does not use random sampling, it just crashes when it does not find metis. Overall, I am fairly sure that my `ClusterGCN` procedure works correctly and implements exactly the procedure that is mentioned in the paper, but I am aware that the example does not reach the correct accuracy yet. This may well be because we use a different architecture here. This is on my todo, and I will look into it, but I wouldn't mind if you would also have a closer look!

**Comment by shaanchandra** [comment]
Hi @rusty1s ,

Thanks again for the quick response!
And that makes it clearer now.

Re: lower performance, I will definitely be looking into it as well in the next few days. I will keep you posted if I find anything. 

Cheers!

**Comment by rusty1s** [comment]
Lower performance was due to not performing inference on the full-graph. It is fixed now :)
