### ISSUE TITLE
Errors on Link Prediction Example

### ISSUE THREAD

**Issue by DavideBuffelli** [rusty1s/pytorch_geometric#1121]
Hi, I'm trying to implement a link prediction GNN using PyTorch Geometric and I think I have found several errors in the example provided in:
https://github.com/rusty1s/pytorch_geometric/blob/master/examples/link_pred.py

In particular, in line 23 the edges are divided in train/val/test, however the method doesn't generate negative training examples and so these are obtained in lines 61 to 67. In my opinion, the operations performed are not correct because from lines 61 to 67 the code is generating negative examples (stored in `neg_edge_index`) starting from the positive training ones, but this means that `neg_edge_index` can contain edges that are actually present in the positive and negative validation/test sets. In fact I checked by simply iterating the negative training examples in `neg_edge_index` and controlling if they are also in the test/validation negative or positive examples, and this happens for several of them, which is clearly not correct.
It's not clear to me why the method `train_test_split_edges` from `torch_geometric.utils` would not output negative training examples, but only validation/test ones.

Furthermore it's not clear to me why in the `test()` method message passing is only performed on the subgraph spanned by the positive validation/test edges. I believe the message passing should always be applied to the graph spanned by the **positive training** edges, and then the classifier should produce the output only for the validation/test edges (both positive and negative).

Thank you in advance for your time.

@dongkwan-kim I though I might quote you since I saw you were the one mainly working on this

**Comment by DavideBuffelli** [comment]
@dongkwan-kim I though I might quote you since I saw you were the one mainly working on this

**Comment by dongkwan-kim** [comment]
To summarize this issue, there are two error reports and one question.

R1. Negative samples used for training may be included in the validation/test sets.
R2. `test()` method uses only test edges, not full edges of the graph.
- For R1 and R2, you are right. It was my mistake. I will try to make a PR as soon as possible, but it may be delayed due to my schedule.
- In my defense for R1, `link_preds.py` is a toy example created during separating train_test_split_edges from the GAE implementation. There seems to be a similar problem.

Q1. Why `train_test_split_edges` would not output negative training examples, but only validation/test ones.
- This also borrows from the GAE implementation. Of course, we can fix the set of negative training samples before training. However, if we do this way, we need to draw negative training sets as many as the number of the specified training epoch. In terms of time and memory management, I think the current method is better.

**Comment by rusty1s** [comment]
R2 is indeed a bug and should be fixed. It would be great if you can do that @dongkwan-kim . Regarding R1, I see no problem here since we cannot expect to have access to positive valid and test edges during training. So having negative sampled edges that are actual positive cannot be prevented.

**Comment by DavideBuffelli** [comment]
Thank you both very much for your help and your quick answers :clap:
