### ISSUE TITLE
Implement CIFAR-10 dataset to the pytorch_geometric dataset

### ISSUE THREAD

**Issue by ttww97** [rusty1s/pytorch_geometric#1265]
## ❓ Implement CIFAR-10 dataset to the pytorch_geometric dataset

Hi, I'm very new to the pytorch_geometric and gnn. Now, I'm trying to do the image classification based on the CIFAR-10 via GNN. However, I'm not quite sure how to convert the CIFAR-10 from torchvision to the pytorch_geometric.data. I know there is a ```ToSLIC``` function, but the return type is still the torchvision class.

Hope anyone can help me with this question. Thanks!

**Comment by rusty1s** [comment]
Can you show me an example of what you are doing? It might be easier for me to help you then :)

**Comment by arshishir** [comment]
I am also planning to do that. I started by trying to understand a little simpler problem like `MNIST`. Since there are a bunch of papers (including @rusty1s's paper) that have studied `MNIST` using GNN (spectral and spatial based methods). 

In `CIFAR-10`, the node will have 3 features (`RGB`) compared to MNIST, where the node has 1 feature (Grayscale value).  You can start with the grid graph unless you are planning to do `superpixel`. Once you are confident with `MNIST` then you should be able to modify `MNIST` code for `CIFAR-10`. 

I am also new to  GNN and pytroch (and python). I have learned a lot by interacting with @rusty1s and going through `PyG` documentation (which is well written), example codes, and `PYG`'s source code. I would love to help and learn from you. So, please post your code or show your example.

**Comment by ttww97** [comment]
Thanks for your reply. This really inspires me. I have used `quick shift` to transform images. It seems working.
