### ISSUE TITLE
GraphSAGE example

### ISSUE THREAD

**Issue by yuanx749** [rusty1s/pytorch_geometric#1460]
## ❓ Questions & Help

Hi,
In [examples/reddit.py](https://github.com/rusty1s/pytorch_geometric/blob/master/examples/reddit.py) (line 61), why is relu not applied to x in the last layer in the inference method? Shouldn't activation function be used at each layer?

**Comment by rusty1s** [comment]
The last layer typically does not contain an activation function since you do not want to restrict the output of your model, *e.g.*, for regression.
For inference, we are only interested in the `argmax` of the output, and this does not get changed by the `log_softmax` call, so this operation is not really of need here.

**Comment by yuanx749** [comment]
Thank you, you're right. I was thinking in unsupervised learning like Deep Graph Infomax, whether activation function should be used in the last layer to get the node representation. I will try both to see which gets better performance.
