### ISSUE TITLE
Is it ok to use batch_size=1?

### ISSUE THREAD

**Issue by Optimox** [rusty1s/pytorch_geometric#1641]
## ❓ Questions & Help

I was looking at this example: https://github.com/rusty1s/pytorch_geometric/blob/master/examples/ogbn_proteins_deepgcn.py

You don't seem to define a batch size and from here: https://github.com/rusty1s/pytorch_geometric/blob/2b303b9ff504e073d2b4fc6d1c82edf7cd198da6/torch_geometric/data/dataloader.py it looks like default batch_size is set to 1.

I wonder if this is on purpose, is it ok to use a batch size of 1? Since this is a node prediction problem, I think it might be ok? What is the rule for batch size for GNN?

Thank you!

**Comment by rusty1s** [comment]
For the `RandomNodeSampler`, its batch size is defined by `num_nodes / num_parts`. Here, we create batches of nodes rather than for graphs (note that this is a different loader than the classical `DataLoader`). Hence, its batch size is far larger than a single node.

A a general rule is that your batch size should fully utilize your GPU, which is exactly what we are trying to do here.

**Comment by Optimox** [comment]
ok thank you!
