### ISSUE TITLE
Why the number of node attribute  of  dataset ENZYMES is 3. But the node attribute dimension of the ENZYMES on the original website is 18. 

### ISSUE THREAD

**Issue by jwwu666** [rusty1s/pytorch_geometric#1646]

**Comment by rusty1s** [comment]
You can include the continuous node features via `TUDataset(..., use_node_attr=True)`, see [here](https://pytorch-geometric.readthedocs.io/en/latest/modules/datasets.html#torch_geometric.datasets.TUDataset). We exclude them by default so that comparison to kernel methods that can only operate on discrete node features is more fair.

**Comment by jwwu666** [comment]
> You can include the continuous node features via `TUDataset(..., use_node_attr=True)`, see [here](https://pytorch-geometric.readthedocs.io/en/latest/modules/datasets.html#torch_geometric.datasets.TUDataset). We exclude them by default so that comparison to kernel methods that can only operate on discrete node features is more fair.

When use_node_attr is True, the dataset.num_classes is 18. Does this mean the number of node class is 18?  I want to classify
graphs of ENZYMES and the number of graph classes is 6. What I should do? Can I do graphs classification of ENZYMES when the number of node attributes is 18 and the number of graph classes is 6?
