### ISSUE TITLE
Questions about the GraphSAGE example

### ISSUE THREAD

**Issue by JunweiSUN** [rusty1s/pytorch_geometric#1726]
## ❓ Questions & Help

Hi @rusty1s , I have a question about your [GraphSAGE reddit example](https://github.com/rusty1s/pytorch_geometric/blob/master/examples/reddit.py):

In training phase, the `NeighborSampler` samples the 2-hop neighbors of each node (25 nodes for 1-hop and 10 for 2-hop), which is similar to the original paper. However in the testing phase, the parameter `sizes` in `NeighborSampler` is [-1], it seems that you only use a test node's all 1-hop neighbors, and use it to do forward process on a 2-layer model. I wonder if we should sample 2-hop neighbors as well? (like sizes=[-1, -1]).

Besides, why you use a `NeighborSampler` instead of `ClusterLoader` in the testing phase in the [cluster-gcn example](https://github.com/rusty1s/pytorch_geometric/blob/master/examples/cluster_gcn_reddit.py)?

Best regards!

**Comment by rusty1s** [comment]
You can also sample the complete 2-hop neighborhood, but this is rather expensive (especially for Reddit). We apply here trick here to compute the node embeddings efficiently: Instead of sampling multiple layers for a mini-batch, we instead compute the node embeddings layer-wise. Doing this exactly two times mimics a two-layer GNN.

**Comment by JunweiSUN** [comment]
@rusty1s Thanks a lot!
