### ISSUE TITLE
Pytorch3d compatibility with Pytorch_Geometric

### ISSUE THREAD

**Issue by albertotono** [rusty1s/pytorch_geometric#1768]
## ❓ Questions & Help

Are the 2 compatibles?

**Comment by rusty1s** [comment]
Yes, PyTorch3d builds upon PyG.

**Comment by VokCow** [comment]
Hi,

Are you sure you are refering to [Pytorch3D](https://github.com/facebookresearch/pytorch3d) and not to [Torch Points 3D](https://github.com/nicolas-chaulet/torch-points3d/tree/master/docs)?

I say it because the latter clearly builds on Pytorch Geometric, but not the former. I cannot find any Pytorch Geometric dependency in Pytorch3D, and it is being a bit of a headache to get both (Pytorch3D and Pytorch Geometric) working together.

Best regards,

Víctor
