### ISSUE TITLE
About graphsaint operation

### ISSUE THREAD

**Issue by srtianxia** [rusty1s/pytorch_geometric#1782]
https://github.com/rusty1s/pytorch_geometric/blob/af675c5bd290314e6c5d66aedb910bbbb952d86b/torch_geometric/data/graph_saint.py#L149

how to understand this operation `row[edge_idx]` ?  I know that this operation should be to sort row according to edge_idx, but I can’t understand why the sorted row_id (id of node) can correspond to edge_count one by one.

**Comment by rusty1s** [comment]
Yeah, this operation sorts `row` according to the original sorting of `edge_index`.

**Comment by LiweiDeng0830** [comment]
I have the same question about it.
```python
import torch
from torch_sparse import SparseTensor

self.adj = SparseTensor(
            row=torch.tensor([0, 1, 4, 3, 0, 0]), col=torch.tensor([2, 2, 3, 2, 4, 3]),
            value=torch.arange(6),
            sparse_sizes=(5, 5))

row, _, edge_index = adj.coo()
print(row)
print(edge_idx)
print(row[edge_idx])
```

The output has been shown in the blow.
```python
tensor([0, 0, 0, 1, 3, 4])
tensor([0, 5, 4, 1, 3, 2])
tensor([0, 4, 3, 0, 1, 0])
```

The constructed `self.adj` should be like this.
```python
[
    [*, *, 0, 5, 4], 
    [*, *, 1, *, *],
    [*, *, *, *, *], 
    [*, *, 3, *, *],
    [*, *, *, 2, *]
]
```
In which `*` means there is no edge between the two node.

So I wonder know why the node index is `tensor([0, 4, 3, 0, 1, 0])` rather than `tensor([0, 1, 4, 3, 0, 0])` which is the row index corresponding to the `edge_idx`?

I am so confuse about it. Can you help me to correct my wrong?

**Comment by rusty1s** [comment]
Seems like this is indeed a bug. To reconstruct one needs to do the following instead:
```python
out = torch.empty_like(edge_count).scatter_(0, edge_idx, node_count[row])
out == tensor([0, 1, 4, 3, 0, 0])
```
Thanks for this careful investigation, this is fixed now!
