### ISSUE TITLE
Question about the SIGN implementation

### ISSUE THREAD

**Issue by JunweiSUN** [rusty1s/pytorch_geometric#1814]
## ❓ Questions & Help

Hi, @rusty1s , I found that there is an SIGN implementation in this repo, are you guys implement this by the description of the original paper or is there any original code (since I didn't find a code link in the paper)? BTW, it seems that there has been only 1 operator while the original paper described up to 8 ops, is there any plan to add the rest ops in the future? Thanks a lot!

**Comment by rusty1s** [comment]
I just implemented it directly from the description in the paper. It seems that the paper changed quite a bit since I last looked at it. The current implementation only supports the "standard" formulation where node features are pre-computed via `A^k @ X` (with `A` being the symmetrically normalized adjacency matrix).
