### ISSUE TITLE
About the pooling layers

### ISSUE THREAD

**Issue by logsea** [rusty1s/pytorch_geometric#1820]
## ❓ Questions & Help

I have some question about the detail of the pooling layers and dense pooling layers.
1. A pooling layer will drop some nodes, and what will it affect edge_index? If `A` and `C` have edge to `B` and `B` has been removed, will there a new edge between `A` and `C` or it will just ignore the edge.
2. Why pooling layer like `TopKPooling` have an ratio to control the output but `dense_diff_pool` do not have. Is that means there is no exact round to pool an graph to 1 point?

**Comment by rusty1s** [comment]
Hi!

1. That depends on the pooling layer. For example, the Graph U-net layer adds 2-hop layers to the graph before dropping the nodes. DiffPool does not have this problem since it clusters nodes together (resulting in a union of neighborhoods)
2. DiffPool controls the ratio of pooled points by the number of learned clusters in the previous GNN.

**Comment by logsea** [comment]
Hi, thank you for your reply and I want to confirm what I understand.

Is the Graph U-net model will add edges by `self.augment_adj` method, but `TopKPooling` only delete edges by `filter_adj`? Maybe that means I can simply copy the `augment_adj` to add edges in any process.

For the second question, I understand the `dense_diff pool` by your reply and the diffpool example.

**Comment by rusty1s** [comment]
Yes, you can enhance TopKPooling via two-hop neighbors by using the `augment_adj` function.

**Comment by logsea** [comment]
Thank you very much! @rusty1s
