### ISSUE TITLE
Is it possible to make MessagePassing.propagate run concurrently?

### ISSUE THREAD

**Issue by chunyuma** [rusty1s/pytorch_geometric#1843]
## ❓ Questions & Help
Hi @rusty1s, I'm using the [GATconv](https://pytorch-geometric.readthedocs.io/en/latest/modules/nn.html#torch_geometric.nn.conv.GATConv) layer in my model. Since my graph is pretty large which has around 4M nodes, it needs to spend ~1 hour to train my model which has 3 GATconv layers in one epoch. I read the original paper of GATconv and it seems like we can update each node in parallel. So I'm wondering if there are any parameter settings in pytorch geometric that can make MessagePassing.propagate run concurrently? Thank you!

**Comment by rusty1s** [comment]
I guess you are training in full-batch mode on CPU, is that correct? I wouldn't recommend that since full-batch computation is expensive (especially on CPU) and has slow convergence. Have you looked at our scalable algorithms to train GNNs, such as our [GAT NeighborSampler example](https://github.com/rusty1s/pytorch_geometric/blob/master/examples/ogbn_products_gat.py)?

**Comment by chunyuma** [comment]
Thanks for your quick reply @rusty1s. Yes, you're right. I used the full-batch mode. Thanks for your suggestion. Using the NeighborSampler might be useful.
