### ISSUE TITLE
Is it possible to run NeighborSampler faster?

### ISSUE THREAD

**Issue by chunyuma** [rusty1s/pytorch_geometric#1877]
## ❓ Questions & Help

Hi @rusty1s, I'm using [NeighborSampler](https://pytorch-geometric.readthedocs.io/en/latest/modules/data.html#torch_geometric.data.NeighborSampler) to get a 3-hop subgraph. But when the size of target nodes is large or the original whole graph is big, running NeighborSampler to get a 3-hop subgraph is slow. So I have a few questions below for running NeighborSampler.

1. I know there is a parameter `num_workers ` in `NeighborSampler` which is used for `torch.utils.data.DataLoader`. But it seems like this parameter is only used to adjust the process of CPU but not GPU. I'm wondering if `NeighborSampler` can run on GPU. If so, are there any parameters in `NeighborSampler` that I can use multiple GPUs given that I have multiple GPUs in my computer.

2. If I don't need to do any sampling for a target node but instead need all the neighbor nodes of a target node, Is it possible that I can turn off sampling within `NeighborSampler` and make it run faster?

Thank you!

**Comment by rusty1s** [comment]
`NeighborSampler` does only work on CPU, and there are no plans to provide a GPU version yet: We rely on `num_workers` to pre-fetch the data while the GPU is busy training (which shouldn't be a bottleneck for shallow networks).
We have a multi GPU neighborsampling example though, see [here](https://github.com/rusty1s/pytorch_geometric/blob/master/examples/multi_gpu/distributed_sampling.py).

If you encounter scalability issues, then this is likely because neighbor sampling does not really scale to deeper networks (even 3-hops can result in a huge receptive field depending on the sampling size). Note that you can include all neighbors by passing `-1` to `sizes`, *e.g.*, `sizes=[10, -1, 5]`.
