### ISSUE TITLE
Autoencoder in inference mode

### ISSUE THREAD

**Issue by nassarofficial** [rusty1s/pytorch_geometric#1909]
## ❓ Questions & Help

Hello, I am trying to use the variational auto encoder [here](https://github.com/rusty1s/pytorch_geometric/blob/702e0ca2aac1b4dd3c811e5b1710f92ed05e7de0/torch_geometric/nn/models/autoencoder.py) in test or inference mode. However, as you can see on this [line](https://github.com/rusty1s/pytorch_geometric/blob/9faf964400d08d9345548d95e183551dfb38ec1c/examples/autoencoder.py#L103), the encoder requires an input of "train_pos_edge_index". But during a case of inference for example, what would be the input since I wouldn't know which edge indices of my graph are positive or negative?

**Comment by rusty1s** [comment]
The use-case of the autoencoder example is to reconstruct *some* missing edges. Therefore, it needs some basic graph to begin with (where some positive edges are missing). If you want to generate graphs completely from scratch, you might want to use its variational variant (by sampling an embedding from a normal distribution). There also exists a lot of research regarding graph generation with GANs, but PyG does not yet provide an example for this line of research.

**Comment by nassarofficial** [comment]
Thank you very much for the quick response. So I am to understand that "generate graphs" relates to passing a graph with all its edge indices needing link prediction? I am particularly looking for a GNN solution that would perform link prediction for such case, is that what a variational gae would do?

**Comment by rusty1s** [comment]
I'm not sure what you mean. Can you clarify? AFAIK, these are two separate use-cases. You either want to create a graph completely from scratch, our you want to do link prediction on an incomplete graph. The autoencoder example does the latter, which always requires an (incomplete) graph as input.

**Comment by nassarofficial** [comment]
I see I had the wrong understanding that the autoencoders would would do link prediction on a complete graph. To clarify, so for the use case in which I would like to train a GNN to take in full graph with a ground truth saying which edge indices are links [0,1], then classify these edges to assign a similarity between nodes on unseen graphs for testing or inference, is not considered a "link prediction" task, if not what's term or method?

**Comment by rusty1s** [comment]
This seems to be related to [Neural Relational Inference](https://arxiv.org/pdf/1802.04687.pdf) where you want to find meaningful connections in a "full" graph.

**Comment by nassarofficial** [comment]
That's very interesting, thanks a lot for answering my many questions. But is that related to only autoencoders or you think the same can be approached with an EdgeConv with MLP.

**Comment by rusty1s** [comment]
Well, this is related to autoencoders, but the Encoder-GNN operates on the full graph instead of an incomplete graph. Since you are operating on the full graph, you need to make use of more expressive GNNs, i.e., one that makes use of both source and target node information, or by creating meaningful edge features. `EdgeConv` looks like a good GNN to use in this scenarios (and is also quite similar to the one Thomas is using in its work). In contrast, something like `GCNConv` can not learn any meaningful pattern in this scenario.

Note that since you want to operate on the full graph, I suggest to implement the GNN-Encoder module by yourself. PyG's operators work on sparse input graphs, and are therefore not that well suited for operating on full graphs.

**Comment by nassarofficial** [comment]
Thanks again for the detailed explanation, I will aim at implementing for PyG.
