### ISSUE TITLE
How to locally pool nodes after KNN clustering

### ISSUE THREAD

**Issue by kheyer** [rusty1s/pytorch_geometric#2086]
## ❓ Questions & Help

Hello,

I'm trying to implement the [Point Transformer](https://arxiv.org/pdf/2012.09164.pdf) paper. One of the modules the paper uses coarsens point clouds using the following process:

1. Use furthest point sampling to select points
2. Use KNN to find neighbor points to selected points
3. Locally max pool over neighbors

With code:
```
# Furthest point sampling
idxs = fps(positions, batch, ratio)

# KNN clustering
assignments = knn(positions, positions[idxs], n_neighbors, 
                                  batch, batch[idxs])

# Max pool over assignments
# This is where I'm stuck

```
The first two steps were straightforward, but I don't know how to use the output from `knn` as an input to `max_pool_x`. `knn` outputs a set of paired indexes. So if you have N points after sampling and K neighbors, the output of `knn` is a `2x(N*K)` tensor. However, local clustering methods like `max_pool_x` require a vector of cluster assignments of size `N`.

How can I convert the output of sampling/KNN to an acceptable input for a local pooling function?

Thanks

**Comment by ldv1** [comment]
You could define a new `edge_index` (in fact a new graph, but the data X is the same) out of your assignment matrix where each node points to furthest points. The graph is then directed. Evidently, there must be no self-loops. Then apply `max_pool_neighbor_x`. This function automatically adds self-loops. So at the end, you would get at each further point a max pool over the nearest neighbors and the further point itself. Is that what you want?
I admit, it is not straightforward and not efficient because max pooling is done over all nodes.

**Comment by rusty1s** [comment]
```python
from torch_scatter import scatter

idx = fps(positions, batch, ratio)
row, col = knn(pos, pos[idx], n_neighbors, batch, batch[idx])
out = scatter(x[row], col, dim=0, dim_size=idx.size(0), reduce='max')
```
should do the trick :)

**Comment by ldv1** [comment]
It does the trick because `knn` returns something that is formatted as `edge_index`. Maybe you could update the documentation in this respect. Thanks.

**Comment by kheyer** [comment]
Thanks for the replies. The posted solution works great!
