### ISSUE TITLE
NNConv is fully-connected or uses only edge_index?

### ISSUE THREAD

**Issue by edgarsmdn** [rusty1s/pytorch_geometric#2090]
## ❓ Questions & Help

Hi,
I would like to clarify if the implementation of NNConv is one where **virtual edges** are created and a fully-connected graph is used.
Or the message passing is performed **only** between the connected nodes determined by the **edge_index**?

I am asking this, since in the Gilmer et al paper two main cases are mentioned:
- Fully connected graph with virtual edges
- Graph with a master node

But nothing about this is mentioned in the docs of NNConv.

Thank you!

**Comment by ldv1** [comment]
`NNConv` as implemented in PyG is a message-passing scheme using `edge_index`.

**Comment by MatthewMasters** [comment]
I'm slightly confused with this too. In both NNConv examples, `edge_index` is a fully-connected graph. This makes sense with [Example2](https://github.com/rusty1s/pytorch_geometric/blob/master/examples/mnist_nn_conv.py) because it's using MNIST images. But why are the molecular graphs in [Example1](https://github.com/rusty1s/pytorch_geometric/blob/master/examples/qm9_nn_conv.py) converted to fully-connected graphs?

**Comment by rusty1s** [comment]
The MNIST example does not operate on fully-connected graphs, but uses k-NN graphs instead. For the latter, we tried to follow its [official experimental setup](https://arxiv.org/abs/1704.01212), which suggests utilizing the fully-connected graph when operating on molecules.

**Comment by MatthewMasters** [comment]
Thank you for the clarification @rusty1s !

**Comment by edgarsmdn** [comment]
Thank you for the clarification!
