### ISSUE TITLE
questions on the class Dataset

### ISSUE THREAD

**Issue by ldv1** [rusty1s/pytorch_geometric#2095]
Hi,

w.r.t to

`class MyOwnDataset(Dataset):`

1/ Should I understand that the method `process` is called each time I instantiate the class? But if the raw files were already processed the way I wanted (with some `pre_filter` and `pre_transform`), how can I avoid this step?
2/ How to set `num_class` for the dataset?
3/ There is nothing to do for `transform`, the transformations will be automatically applied each time `get()` is called, right? depending on the transformation, that means  a bit of work for each sample at each epoch; correct?

**Comment by rusty1s** [comment]
1. `process` will only get called in case processed files are not found or the `process` method is not implemented.
2. They are automatically determined in case `data.y` is present in the data. Otherwise, you can overwrite the property by yourself.
3. Exactly. In case transformation will be slow, we recommend to outsource them via `pre_transform`.

**Comment by ldv1** [comment]
thanks
