### ISSUE TITLE
How to install by conda?

### ISSUE THREAD

**Issue by FLHonker** [rusty1s/pytorch_geometric#229]
## ❓ Questions & Help

How to install by conda?
It only can be installed by pip now?It doesn't work, please!

**Comment by rusty1s** [comment]
We plan to allow conda installation in the near future. However, this will not prevent your error from https://github.com/rusty1s/pytorch_geometric/issues/226, because you will still need to compile CUDA extensions manually. I'm closing this issue in favor of https://github.com/rusty1s/pytorch_geometric/issues/226 to help you.
