### ISSUE TITLE
Possible mistake in ARMAConv

### ISSUE THREAD

**Issue by sw-gong** [rusty1s/pytorch_geometric#232]
```
    def forward(self, x, edge_index, edge_weight=None):
        """"""
        if edge_weight is None:
            edge_weight = x.new_ones((edge_index.size(1), ))
        edge_weight = edge_weight.view(-1)
        assert edge_weight.size(0) == edge_index.size(1)

        row, col = edge_index
        deg = scatter_add(edge_weight, row, dim=0, dim_size=x.size(0))
        deg_inv = deg.pow(-0.5)
        deg_inv[deg_inv == float('inf')] = 0

        lap = -deg_inv[row] * edge_weight * deg_inv[col]
```

From the formula of ARMAConv provided in the documentation, the neighboring node featuers after linear transformation are normalized by 1/sqrt(deg(i)* deg(j)) for edge(i, j) \in E. Thus, `deg=degree(row, x.size(0), dtype=x.dtype)`. It's not clear for me why you `scatter_add` `edge_weight` here considering you already take edge_weight into account when compute `lap`. Let's say if the given parameter is weighted adjacency matrix (WA_ij) instead of adjacency matrix (a_ij where a_ij \in {0, 1}). The formula would become D^(-1/2)WA D^(-1/2), thus `lap = deg_inv[row] * edge_weight * deg_inv[col]` would be fine, and there is no need to consider `edge_weight` when calculating `deg`.

Another thing I'm not quite clear is that why you negalat `deg_inv[row] * edge_weight * deg_inv[col]` when computing `lap`. The formula here is positive (LXW, thus D^(-1/2)AD^(-1/2) X W).

Thank you.

**Comment by rusty1s** [comment]
Hi,
the modified Laplacian (Eq. 10) is defined as \hat{L} = I - L where L = I - D^{-0.5} A D^{-0.5}. Hence, \hat{L} = D^{-0.5} A D^{-0.5}. We `scatter_add` the edge weights to obtain D, because D denotes the **weighted** degree matrix, which is defined as D_{i,i} = sum_{j=1}^N A_{i,j}. 

The negation of `lap` is indeed a bug  where i misread the laplacian formulation. It is fixed in master. Sorry!

**Comment by sw-gong** [comment]
I see. Thank you.
