### ISSUE TITLE
Some operation for MultiDiGraph?

### ISSUE THREAD

**Issue by chunyuma** [rusty1s/pytorch_geometric#2361]
From now on, we recommend using our discussion forum (https://github.com/rusty1s/pytorch_geometric/discussions) for general questions.

## ❓ Questions & Help

Hi @rusty1s, 

I'm wondering if pytorch geometric allows some operation for MultiDiGraph (directed graphs which allow multiple edges between any pair of nodes. For example, nodeA-relation1-nodeB, nodeA-relation2-nodeB, nodeA-relation3-nodeB). Based on the dim of `edge_index` [2, num_edges], if pytorch geometric allows MultiDiGraph, then the `edge_index` might have many duplicate columns (e.g. [[1,1,1,2],[0,0,0,1]]). In this case, I'm wondering if the functions like `k_hop_subgraph` or `negative_sampling` still work and consider multiple edges between any pair of nodes. 

In addition, for the `aggregate` function, its parameter `index` is edge_index[1]. If my graph is MultiDiGraph, is it possible to use `scatter` to calculate the mean of multiple edges between a pair of nodes? If the answer is yes, then how can I know the `index` for both source node and target node?

Thank you!

**Comment by rusty1s** [comment]
Functions like `k_hop_subgraph` and `negative_sampling` still work in this case.

I'm not sure if there is an elegant way to calculate the `mean` of multi-edges without O(n^2) complexity. In this case, you can always do something like:
```python
index = edge_index[0] * num_nodes + edge_index[1]
scatter(index, edge_weight, dim_size=n^2, reduce="sum")
```
Since `index.max()` might be N^2 -  1`, a potential solution is to make use of `torch.unique` on `index` to convert `index` into consecutive indices.

**Comment by chunyuma** [comment]
Ah, I see. thanks @rusty1s!
