### ISSUE TITLE
Add entropy regularization to DiffPool

### ISSUE THREAD

**Issue by sw-gong** [rusty1s/pytorch_geometric#237]
Hi,

As for the dense_diff_pool, the first two lines of the below code should be the auxilliary link prediction objective, so why it needs to be devided by `adj.numel()`? Additionally, it seems you didn't implement Entropy Regularization L_E? Can you please explain it? 

```
reg = adj - torch.matmul(s, s.transpose(1, 2))
reg = torch.norm(reg, p=2)
reg = reg / adj.numel()
```

Thanks.

**Comment by rusty1s** [comment]
Hi the link loss should actually be independent of the number of nodes. This is not specified in the paper, [but actually done in the reference implementation](https://github.com/RexYing/diffpool/blob/master/encoders.py#L397). Regarding the entropy regularization, we shall integrate it. I didn't even know it existed, because this was added in a later version of the paper.

**Comment by sw-gong** [comment]
I see. Thanks for your clear clarification. Hope to see the entropy regularization.

**Comment by rusty1s** [comment]
I added the entropy loss to `dense_diff_pool`.

**Comment by sw-gong** [comment]
*examples/enzymes_diff_pool.py*
 `link_loss` and `ent_loss` should be added into the right side of this line `loss_all += data.y.size(0) * loss.item()`.

Thanks.

**Comment by rusty1s** [comment]
Yes, fixed!
