### ISSUE TITLE
A question about the design choice - sparse mm vs scatter

### ISSUE THREAD

**Issue by chentingpc** [rusty1s/pytorch_geometric#261]
Thanks for the great library! This is a question regarding to the design choices of using "indexing+ scatter" as the message propagation operator (in many cases can be expressed as AH where A is a sparse adj matrix, and H is dense node hidden state matrix). And the sparse mm is only utilized few times. I was wondering if this is due to the efficiency concerns, or simply API convenience? Could you please elaborate? Thanks in advance!

**Comment by rusty1s** [comment]
Hi, there is not a single place in PyG where we use spmm instead of gather and scatter. Thus is due one the one hand due to efficiency, on the other it allows fir a more flexible message passing (e.g. integrating edge features). Please see Appendix A of our [paper](https://arxiv.org/abs/1903.02428) for more details.

**Comment by tformal** [comment]
hi @rusty1s , thanks for the clarification ! 
Could you provide additional hints on why the gather+scatter scheme "can still be improved" for dense graph settings ?

**Comment by rusty1s** [comment]
Hi,
scatter ops rely on atomic operations, which ideally run in constant time. However, with higher degrees, you have more threads which want to write the same storage (which slows down scatter ops and favors sparse matmuls).

**Comment by tformal** [comment]
Hmm ok I see, that makes sense ! Thanks for the clarification !
