### ISSUE TITLE
RGCNConv and FastRGCNConv do not have self-loops ?

### ISSUE THREAD

**Issue by jaynanavati-az** [rusty1s/pytorch_geometric#2690]
Hello, it seems like the implementations do not follow the paper w.r.t to self loops: https://arxiv.org/pdf/1703.06103.pdf

**Comment by rusty1s** [comment]
Can you explain? We add transformed central node features to the output, just as defined in Eq. (2).

**Comment by jaynanavati-az** [comment]
Could you please point in the code? I am not able to find this

**Comment by rusty1s** [comment]
Sure, here: https://github.com/rusty1s/pytorch_geometric/blob/master/torch_geometric/nn/conv/rgcn_conv.py#L216-L218

**Comment by jaynanavati-az** [comment]
Okey, thanks - sorry it might be the case the documentation could be improved? as in the paper they explicitly mention adding self loops for this purpose?

**Comment by rusty1s** [comment]
I think this is already mentioned in the documentation, where the formula explicitly mentions `W_{root} @ x` (see [here](https://pytorch-geometric.readthedocs.io/en/latest/modules/nn.html#torch_geometric.nn.conv.RGCNConv)). Otherwise, please feel free to suggest the changes that you would like to see :)

**Comment by jaynanavati-az** [comment]
Ah, yes you are right indeed! I was going by the formula in the paper, so it got a bit confusing since they are slightly different from the doc. Thanks for your help :)
