### ISSUE TITLE
Ensuring that all possible negative edges are considered

### ISSUE THREAD

**Issue by mahadafzal** [rusty1s/pytorch_geometric#2973]
I have been working with a custom dataset and took inspiration from the link_pred.py example in the repository. I have had the model working after some issues and am getting good results. However, in order to make my results comparable to previous work, I need to ensure that when testing, all possible edges in a graph, both positive and negative, are considered.

From what I understand, the example considers all positive edges but downsamples to a much smaller size of the negative sample set, as done in the GAE paper as well. I have tried to work around this by training and testing on the probability adjacency matrix output from the model, but the results seem to be very poor. Is there a way to ensure that all possible edges are considered and predicted on in a graph when working with the link prediction model?

**Comment by rusty1s** [comment]
Training and testing is usually only performed on a subset of negative examples due to memory limitations. Furthermore, testing against all possible negative edges is quite challenging, due to the larger amount of negative samples.

I think what you are doing is already correct for evaluation (if you have doubts please feel free to post a code snippet). As the decoder in the `link_pred` example is quite dumb, you might also see more success when using more sophisticated decoders (such as running an MLP on the concatenated feature values of source and target nodes).

**Comment by mahadafzal** [comment]
I represented the dataset I am working with as a list of graphs, and each graph tends to be small (I believe the biggest graphs I have are around 10-15 nodes), so memory limitations should not be an issue. The previous work that I am trying to compare application of GNN too are SVM/LSTM with attention based, so it is important that all edges are considered for GNN as well, in order to make the results comparable. Is there any GNN implementation you have in mind that does so?

Additionally, could you post a short snippet with regard to your MLP decoder suggestion? That could be helpful.

**Comment by rusty1s** [comment]
I see. In this case, I think you are save to simply use all non-positive edges as negative edges, *e.g.*, by storing them in `data.neg_train_edge_index` in a pre-processing step.

For a decoder based on MLP, I have something like this in mind:
```python
def decode(self, z, edge_index):
    z = torch.cat([z[edge_index[0]], z[edge_index[1]]], dim=-1)
    return self.MLP(z)
```
where `self.MLP` is a MLP mapping from `2 * hidden_channels` to `1`.

**Comment by mahadafzal** [comment]
Thank you for the help, will experiment with this!
