### ISSUE TITLE
How to use batch to accelerate the code?

### ISSUE THREAD

**Issue by TianhangWang** [rusty1s/pytorch_geometric#3049]
From now on, we recommend using our discussion forum (https://github.com/rusty1s/pytorch_geometric/discussions) for general questions.

## ❓ Questions & Help

Hi, Thanks for your amazing work for GCN! I want to acquire some thinkings that whether can use batch to accelerate the code?
Here, I got tensor `temporal_window`, the shape is `[batch, 5, 19, 256]`. The `5` represents 5 frames(from past to now), `19` represents 19 objects, `256` represents the object feature. I want to use GCN along time in single object, moreover, the graph is defined easily, all objects' GCN edge_index is [[0, 4], [1, 4], [2, 4], [3, 4]], the edge_weight is [0.01, 0.05, 0.13, 0.36]. So Could you tell me how to use batch to avoid `for loop` in both `batch` and `objects = 19`?

Simple example:
```
self.conv1 = GCNConv(256, 128)

# if do not use batch, I need to use two for loop

for i in range(temporal_window.size(0)): for loop in batch
      batch_0 = temporal_window[i] # shape of batch_0 is [5, 19, 256]
      for j in range(batch_0.size[1]): # for loop in objects
           enc = F.relu(self.conv1(batch_0[:, j, :], edge_index, edge_weight)
```
Then I need use different empty list to get `enc`, finally the output `temporal_gcn_feature` would be shape of `[batch, 19, 128]`
However, this process would take too much time, could you tell me how to accelerate the code? Looking forward to your reply!

**Comment by rusty1s** [comment]
As far as I understand, you do not need to loop over objects as these objects already describe your node dimension. You also do not loop over the batch-dimension, since you can either use a node feature tensor of shape `[batch_size, num_nodes, num_features]` as input to your GNN when operating on static graphs, or use the standard batching procedure of PyG using the `DataLoader` class. If you want to further avoid the loop over timestamps, you can also merge the node and time dimension into a single dimension, and do a simple reshaping after GNN processing, e.g. `[num_nodes * timestamps, features]` to `[timestamps, num_nodes, features]`.

**Comment by TianhangWang** [comment]
Thanks for your reply! I might be a kind of confused. I run the code as below:
```
self.conv1 = GCNConv(286, 128)
print(windows_t.shape)   
# shape: [batch, 5, 19, 256]
print(self.edge_index)  
# tensor([[0, 1, 2, 3],[4, 4, 4, 4]], device='cuda:0')
print(self.edge_weight) 
# tensor([0.0183, 0.0498, 0.1353, 0.3679], device='cuda:0')
t_graph_result = self.conv1(windows_t, self.edge_index, self.edge_weight)
print(t_graph_result)
# torch.Size([8, 5, 19, 128])
```
Does this represent the GCN already graph every object's five contiguous timestamps in each batch? (`19` represents object's number, totally, 19 objects; `5` represents each object's detected features in 5 contiguous timestamps)
So, Could I use `t_graph_result[:,-1, :, :]` to get the objects' last timestamps feature after GCN?

**Comment by TianhangWang** [comment]
So, actually, My graph is just five nodes(represent timestamps), but got `[batch * objects]` numbers graph operation.

**Comment by rusty1s** [comment]
So you want to perform graph convolution over the number of timestamps rather than the number of nodes? In this, you should represent your node feature tensor with shape: `[batch_size * num_nodes, num_timestamps, num_features]` to get the expected result.

I'm still not sure if that's particular useful though, as you can already implement something similar to this in vanilla PyTorch, e.g., via:
```python
x = ... [batch, num_objects, num_timestamps, num_features]
x = self.lin1(x[:, :, -1]) + self.lin2(x[:, : :-1]).mean(dim=-1)
```

**Comment by TianhangWang** [comment]
Here, I got a question, if I use following codes:
```
self.conv1 = GCNConv(286, 128)
print(windows_t.shape)   
# shape: [batch, 5, 19, 256]
windows_t_re = torch.flatten(windows_t.permute(0,2,1,3), start_dim=0, end_dim=1)
print(windows_t_re.shape)
# shape: [batch x 19, 5, 256]
t_graph_result = self.conv1(windows_t_re, self.edge_index, self.edge_weight)
print(t_graph_result.shape)
# shape: [batch x 19, 5, 128]
t_graph_result_re = t_graph_result.reshape(batch, 19, 5, 128).permute(0,2,1,3)
print(t_graph_result_re.shape)
# shape: [batch, 5, 19, 128]
```
So, does this right? also `t_graph_result_re[0,-1,0]` index same objects as `windows_t[0,-1,0]`, as for [0, -1, 0], from left to right, first `0` represent batch_index=0, `-1` represnets last timestanp, last `0` represent object_index=0. In other words, does this reshape operation will change the position of objects in batch?

**Comment by rusty1s** [comment]
This looks correct to me. The position of objects is not changed as far as I see.

**Comment by TianhangWang** [comment]
Thanks!
