### ISSUE TITLE
The number of edges in the Actor dataset does not match the one reported in the paper

### ISSUE THREAD

**Issue by OlegPlatonov** [rusty1s/pytorch_geometric#3060]
Hi! I've noticed that the number of edges in the Actor dataset does not match the one reported in [the Geom-GCN paper](https://arxiv.org/abs/2002.05287). The paper reports 33544 edges while the graph in PyTorch Geometric has only 30019 edges. Also, the number of node features in the same dataset is off by one.

**Comment by rusty1s** [comment]
Thanks for reporting. I checked with the raw data:
1. The raw node features in `out1_node_feature_label.txt` indeed hold 932 node features instead of 931
2. Edges in `out1_graph_edges.txt` hold 33391 entries. After coalescing (removing duplicates), 30019 edges are remaining.

I'm not sure why the Geom-GCN paper reports numbers that are way of of these, but I'm pretty certain that PyG pre-processes the data correctly given the raw data from the Geom-GCN repository.
