### ISSUE TITLE
Batch-wise to_dense_adj to allow for sparse adjacencies pre DiffPool

### ISSUE THREAD

**Issue by tomcat123a** [rusty1s/pytorch_geometric#388]
## 🚀 Feature

currently the dense_diff_pool accepts graph adjacency matrix as input.Is there a version such that it can accept edge_index, as in GraphConv?

**Comment by rusty1s** [comment]
Hi, no currently it only accepts dense matrices. A sparse version would also produce dense adjacencies, so this is a bit inconsistent. There is also no memory saving by using a sparse version, because we would need to convert the adjacency to a dense one by ourselves. We could offer a `to_dense_adj` batch-wise functionality though. I see what I can do.

**Comment by rusty1s** [comment]
Added in [master](https://github.com/rusty1s/pytorch_geometric/blob/master/torch_geometric/utils/to_dense_adj.py).
