### ISSUE TITLE
add_self_loops() adds loop to exluded nodes in subgraphs

### ISSUE THREAD

**Issue by yutaizhou** [rusty1s/pytorch_geometric#452]
## To Reproduce

```
G = nx.complete_graph(5)
g = pyg.utils.from_networkx(G)
e = pyg.utils.subgraph([0,1,3,4], g.edge_index)[0]

print(e)
# tensor([[0, 0, 0, 1, 1, 1, 3, 3, 3, 4, 4, 4],
          [1, 3, 4, 0, 3, 4, 0, 1, 4, 0, 1, 3]])


print(pyg.utils.add_self_loops(e)[0])
# tensor([[0, 0, 0, 1, 1, 1, 3, 3, 3, 4, 4, 4, 0, 1, 2, 3, 4],
          [1, 3, 4, 0, 3, 4, 0, 1, 4, 0, 1, 3, 0, 1, 2, 3, 4]])
```

As you can see, in the subgraph `g`, only nodes 0,1,3,4 should exist. Node 2 is excluded from the subgraph. However, `add_self_loop()` adds self loop to node 2 as well.

**Comment by rusty1s** [comment]
Use `relabel_nodes` in the `subgraph` call to fix.

**Comment by yutaizhou** [comment]
In my application, the label of the nodes from the original graph must be kept in the subgraph. I think relabeling nodes in this case would be a bad idea. Probably would be better to change `add_self_loops ` to add self-loops only to the nodes present in the edge index. What do you think? Would this change break a lot of things?

**Comment by yutaizhou** [comment]
Another question, for `add_remaining_self_loops()`, why not just call `remove_self_loops()` followed by `add_self_loops()`, rather than re-implementing some of the logic already present in `add_self_loops()`?
This is kind of a trivial implementation detail, but I am just curious.

**Comment by rusty1s** [comment]
I do not find it very intuitive to not add self-loops for isolated nodes. In addition, all message passing operators do it the way we do it in PyG. Hence, it would break a lot of things to change this method. If you really not want to add loops to isolated nodes, you need to filter them out first (in the end, it does not really matter because they are not part of message passing anyway). We provide such functionality with the `relabel_nodes` argument. We do differ from the networkx way here of having explicit node labels due to being close to PyTorch and efficiency.

For `add_remaining_self_loops`, we refactor a lot of the initial code. We cannot implement it the way you describe because we want go remain edge weights for initial self-loops.

**Comment by yutaizhou** [comment]
Ah I misunderstood the role of self-loops in message passing when dealing with isolated nodes. The way I thought about it, an isolated node's features would be included in message passing for other nodes if it has self-loop, which, in retrospect, makes no sense at all since it has no neighbors. 

If a node is isolated, what would be its effect during message passing? Would it just not be factored into other node's feature update, and have its own features be updated as a function of its own feature, the weight matrix, and the normalizing degree matrix? 

Regarding `add_remaining_self_loops`, yes of course. I have not worked with edge weights in my application at all, so that thought escaped my mind. 

Thank you for your explanation!

**Comment by rusty1s** [comment]
For isolated nodes, the normalizing degree matrix has no effect (since we have degree zero), so this basically boils down to a MLP based on initial node features.

**Comment by yutaizhou** [comment]
That makes perfect sense. Thank you!
