### ISSUE TITLE
to_networkx() digraph

### ISSUE THREAD

**Issue by yutaizhou** [rusty1s/pytorch_geometric#453]
## To Reproduce

```
G = nx.complete_graph(5)
g = pyg.utils.from_networkx(G)
G_new = pyg.utils.to_networkx(g)
```
`is_directed()` returns False, False, True, for the three variables above, respectively. It should return `False` for `G_new` as well. 

In **convert.py**, I don't understand the choice of making `G` `nx.DiGraph()` by default in `to_networkx()`. Why not allow `G` to be `nx.Graph()` if the input data is undirected?

**Comment by WMF1997** [comment]
hello @yutaizhou :

First, I reproduce your code again. 

## Environment
Ubuntu 16.04 (WSL)

PyTorch: 1.1.0
PyG: 1.2.0
networkx: 2.1

## My Code
```python
import networkx as nx
import torch_geometric.data as gdata
import torch_geometric.utils as gutils

G = nx.complete_graph(5)
g = gutils.from_networkx(G)
G_ = gutils.to_networkx(g)
G__ = nx.Graph(G_)
```

## 1 about your 3 lines of code
```is_directed()``` should return 
```python 
False, True, True
```
respectively. i.e.  the second of your return result should be True? I don't know what happens in your code. 

## 2 in **convert.py**, ...
In my opinion, 

> the choice of ```G``` making ```nx.DiGraph()``` by default in ```to_networkx()```

is the only choice if use 

I know what you mean. there can be 2 ideas:
### 1 ``` g.to_networkx()```
adding a method/property to ```torch_geometric.data.data.Data```
### 2 check before convert
before converting it to networkx, check if it is an undirected graph, using ```torch``` and ```torch_geometric``` bucket(i.e. ```torch_scatter```, ...)

and if it is an undirected, the returned G is an undirected, else G is a directed. 

## my idea(Conclusion) about this issue

Comparing with 2 ideas(in fact, 2 ideas is the same in implementing...), using ```nx.DiGraph()``` in convert.py is the simplest way, I think. 

## P.P.S 
since your graph is undirected, just do as the last line of my code.
```python
G__ = nx.Graph(G_)
```
and then, ```G__``` is an undirected graph. 

Yours, 
@WMF1997

**Comment by rusty1s** [comment]
I do not think this is a problem at all. PyG only knows about directed graphs, so making `nx.DiGraph()` the default in `to_networkx` makes sense. A simple
```python
G_new = nx.to_undirected(G_new)
```
fixes all your problems :)

**Comment by yutaizhou** [comment]
OH I see. I didn't know the intention is to have PyG only know about directed graphs. My line of thought was just "if an undirected nx graph is convertedinto PyG format, it should still be undirected when it is converted back."

Can you explain the reason behind this design choice? I think this point would be nice to have in the docs somewhere lest someone like me get confused about it again.

**Comment by rusty1s** [comment]
It is actually mentioned in the introduction tutorial. This is a design decision, but it makes message passing operators more elegant and especially independent of the `Data` object. Otherwise, we would need to keep track on whether `data` should be directed or undirected, and replicate reverse edges in the message passing operator in case the graph is undirected.

**Comment by yutaizhou** [comment]
Sorry, I didn't see where it was explicitly mentioned in the doc that PyG only knows about directed graph. I probably should have inferred at 

> Although the graph has only two edges, we need to define four index tuples to account for both directions of a edge.

I understand the choice now. It is an excellent decision. Thank you as always for your explanation!
