### ISSUE TITLE
GCNProp forward operations

### ISSUE THREAD

**Issue by dfdazac** [rusty1s/pytorch_geometric#48]
First of all, kudos for the great library!
I have a question regarding the forward pass of the GCN layer. Before commit 06f4a4d the order of the preprocessing operations was

1. Normalize adjacency matrix
2. Add self-loops to adjacency matrix

I had been experimenting with an older version of the library (the one on PIP actually) that used this order and I was having a hard time getting good performance with my model, and then I noticed that such order was the opposite of how it was proposed it in the original paper and implemented in the [original GCN repository](https://github.com/tkipf/gcn).
I was about to raise an issue but then I noticed that commit 06f4a4d reversed the order, so I pulled the changes and my results are much more different now.
Was there any particular reason for this change? Also, I see that the GCNProp class now has an additional `improved` argument, what is its purpose?
Thanks!

**Comment by rusty1s** [comment]
Hi,

do  you have better performance now?
Actually, there was a small normalization bug. I was computing `D^-0.5 (A + I) D^-0.5` instead of `(D + 1)^-0.5 (A + I) (D+1)^-0.5`, but this should be fixed now.

The `improved` flag refers to the improved GCN propagation of the [Graph U-Net Paper](https://openreview.net/forum?id=HJePRoAct7).

**Comment by dfdazac** [comment]
Yes, the performance is better now. Then what I was obtaining before might have been due to the bug. I'll check the paper, thanks!
