### ISSUE TITLE
Edge-based unpooling

### ISSUE THREAD

**Issue by simofoti** [rusty1s/pytorch_geometric#487]
## ❓ Questions & Help

Hello,

I am currently trying to develop a mesh autoencoder and I was thinking to use an unpooling operation such as the one described in the [Pixel2Mesh paper](https://arxiv.org/pdf/1804.01654.pdf).
I was wondering if you had any suggestion on how to implement it (and in particular how to obtain the new edge connectivity). 

Thanks in advance for your help!

**Comment by rusty1s** [comment]
You need to create a node for every edge in your graph which can be implemented quite straightforward using `row` and `col` from `edge_index`. It is a bit more complicated to obtain the new edge connectivity. I guess you need to hold a map from edge id to new node id, e.g. `f(e) = e + current_num_nodes`. The „outer“ `edge_index` can be then obtained by `[row, f(arange(num_edges))] + [col, f(arange(num_edges))]`. The „inner“ `edge_index` is trickier, because you need the face connectivity of the original mesh. Hope this helps :)

**Comment by simofoti** [comment]
@rusty1s thanks for your quick response.

The inner `edge_index` was my original problem indeed. In your opinion, would it be reasonable to retrieve the faces from the edges at each unpooling operation? 

One option would be to Iterate over all the vertices. Consider all pairs of edges adjacent to a given vertex **A**. For a given pair of edges adjacent to **A**, you get a possible triangle **A**, **B**, **C**. This triplet is a triangle only if there is an edge joining **B** and **C**. This could be verified by going through the edge lists of **B** and **C**. However, it seems to be too time consuming (and not sure it would be differentiable). What do you think?

**Comment by rusty1s** [comment]
I thought about this problem a lot, and for me there seems to be no efficient way to tackle the problem of obtaining the inner edge indices. Your approach certainly works, but it will be unusably slow :(

Do you know how the authors of the Pixel2Mesh paper tackle this problem? Since edge connections seem to be deterministic, it might be reasonable to simply pre-process this task once.

**Comment by simofoti** [comment]
I agree, it would be tremendously slow. I tried to come up with a less naive solution during the weekend, but without any success yet. 

I had a quick look at the code of the Pixel2Mesh paper and looks like they are computing the edge connectivity in a pre-processing step (as you said). As far as I have seen, they unpickle a file containing the edge connections at different resolutions.

If I want to perform this type of unpooling in a mesh autoencoder, I guess that the pre-processing step will work as long as:
1. the pooling steps are deterministic as well. 
2. the vertices of all the meshes are properly ordered with respect to the pre-computed edge connectivity or I pre-compute the edge-connectivity at different resolutions for every mesh.

Do you agree? 

Do you have better ideas to create a mesh autoencoder with what is already available in PyG (different types of pool/un-pool)?

**Comment by rusty1s** [comment]
I am not sure if the vertices needs to be in particular order, as long as your encoder is permutation-invariant. It may help in computing the loss though. 

Sadly, we do not offer any unpooling operator for this kind of task, because AFAIK they are all pre-computed :(

**Comment by simofoti** [comment]
I am not sure I have properly understood what you meant by permutation invariant, sorry. Could you give me some reference to what you mean or just a quick explanation? Would it work having as vertex feature 3D coordinates?

That's ok, I think should be feasible to implement the unpooling with a pre-processing step.

**Comment by rusty1s** [comment]
So why do you think the order of the vertices matter? They should get mapped to the same latent space by the encoder independent of their order.

**Comment by simofoti** [comment]
Good point. I'll try to do what we have discussed so far.
Thanks for your useful suggestions! :)

**Comment by JunpengGao233** [comment]
> I am not sure if the vertices needs to be in particular order, as long as your encoder is permutation-invariant. It may help in computing the loss though.
> 
> Sadly, we do not offer any unpooling operator for this kind of task, because AFAIK those unpooling layers are all pre-computed :(


> I agree, it would be tremendously slow. I tried to come up with a less naive solution during the weekend, but without any success yet.
> 
> I had a quick look at the code of the Pixel2Mesh paper and looks like they are computing the edge connectivity in a pre-processing step (as you said). As far as I have seen, they unpickle a file containing the edge connections at different resolutions.
> 
> If I want to perform this type of unpooling in a mesh autoencoder, I guess that the pre-processing step will work as long as:
> 
> 1. the pooling steps are deterministic as well.
> 2. the vertices of all the meshes are properly ordered with respect to the pre-computed edge connectivity or I pre-compute the edge-connectivity at different resolutions for every mesh.
> 
> Do you agree?
> 
> Do you have better ideas to create a mesh autoencoder with what is already available in PyG (different types of pool/un-pool)?



Sorry to reply to a closed issue, but my situations are pretty similar. If the unpooling may not be deterministic, could I ask the feasibility of using other languages like implementing a C++ program to perform operation and insert the network. Because I do not have relative experiences to interact between them, how about the effectiveness? My solution is also not smart.  :(
