### ISSUE TITLE
cartesian or local cartesian for 3D classification

### ISSUE THREAD

**Issue by alekseic** [rusty1s/pytorch_geometric#52]
I just finished reading the SplineCNN paper. Can you suggest, what kind of coordinate normalization is better for 3D classification of objects using SplineCNN, when a 3D triangular mesh is given - the cartesian (where the distances from a vertex to all other points of the 3D mesh are normalized to [0,1]) or the local cartesian (when the distances are normalized by dividing by the maximum vertex-vertex distance in a 1-hop neighborhood - am I correct?) ? What can be the advantages and downsides of these approaches for 3D object classification? I think that there might be different behaviour when a CNN is trained on a fine-grained mesh, and then applied to a coarser triangular mesh, or vice versa. One of these normalization approaches might generalize better... What do you think?
Sorry for posting this as an "issue"

**Comment by rusty1s** [comment]
Hi,
this is a really interesting question. In all my experiments, `LocalCartesian` performed worse, but I actually never played around with generalization to coarser triangular meshes and vice versa. My guess is that these results would still hold, because the choice of the transform does not change the fact that the model needs to generalize to patterns with higher curvatures it never saw before during training.
A better way to solve this could be to append the 2-hop neighborhoods to your edge indices (as long as neighboring nodes lie in a specific defined radius).
