### ISSUE TITLE
Is that possible to convert edge_index back to Face?

### ISSUE THREAD

**Issue by sw-gong** [rusty1s/pytorch_geometric#575]
Assume I have edge_index which is converted from FaceToEdge function, is that any way to convert this edge_index back to Face?

Thanks!

**Comment by rusty1s** [comment]
Sadly no, but you can keep the faces with the `remove_faces=False` argument.

**Comment by sw-gong** [comment]
I see. I asked this because I lost original data (with face), but I still have processed data with edge_index. I want to see if there is any method to recover faces..

**Comment by rusty1s** [comment]
If you know about any reference implementation, feel free to link it here, but this seems to be far from trivial.

**Comment by sw-gong** [comment]
May I ask Why it can't roll back since I created edge_index from FaceToEdge this function?

**Comment by rusty1s** [comment]
You mean why it is non-trivial to convert edge indices to faces?
1. You need to detect all faces by looking at 2-hop neighbors
2. You need to remove all duplicated faces since you will create a face for every edge.
You can achieve this by iterating over all edges in a python loop though, but this is not really convenient.

**Comment by sw-gong** [comment]
I see. Thanks!
