### ISSUE TITLE
Pointnet2 clarification

### ISSUE THREAD

**Issue by antoalli** [rusty1s/pytorch_geometric#671]
## ❓ Questions & Help

Hi, I was looking for a PointNet2 classification backbone implementation in this repo. Actually I found two different backbones (one from 'examples' folder,  the other from 'benchmarks/points' folder).
Could you explain me why there are two models and which is the difference between them? I'm trying to replicate the paper experiments so I'm looking for an implementation as near as possibile to the Tensorflow/paper one.
Thank you in advance!

**Comment by rusty1s** [comment]
The example file tries to be as close as possible to the architecture presented in the PointNet paper (except that it is missing the T-network due to evaluating on ModelNet10). The benchmark script is the one we used to compare point cloud operators (with approximately equal number of parameters), so it does not necessarily match the architecture of the PointNet paper.

**Comment by antoalli** [comment]
Understood, Thanks!
