### ISSUE TITLE
Graph compression

### ISSUE THREAD

**Issue by Blitzman** [rusty1s/pytorch_geometric#83]
First of all, kudos for this great framework that is evolving continuously! Been using it for quite a few months already and I really like it!

For my current project, I am trying to process graphs created from point clouds with a GCN. The catch is that those point clouds come from depth maps of 640x480 pixels so there are as many points. The way to generate graphs is to use k-NN. In such a large cloud it is easy to see that when k starts being significant the graph is going to be quite big in terms of edges. For a basic dataset of 1500 clouds it is impossible to fit into 16 GiB even for k=3 so I am using a custom on the fly dataset loader instead of the in memory one.

Thing is, when graphs are saved in Pickle (.pt) using torch.save, they are huge! For instance, approximately 250 MiB for a 640x480 k=64 graph.  That clearly becomes intractable as the dataset grows...

I was wondering if there is any way to add automatic graph compression/decompression on the fly. I was wondering if the internal data representation is inefficient (i.e., the adjacency matrix is extremely sparse) but since Data stores edges in COO format it doesn't look like a problem or at least it is the minimum amount of memory it can take. Any other idea? How do you deal with such large graphs in this setting?

**Comment by rusty1s** [comment]
Hi and thank you :)

please note that you do not need to actually save PyTorch Geometric `data` to disk. You can save your data in any format you like and transform it in `__getitem__`. For example, edge indices need to sadly have `torch.long` dtype (due to PyTorch indexing reasons), but could actually be stored as `int` tensors (which halves memory footprint). In addition, edge indices could be saved in CSR format and automatically be transformed to COO format when being loaded.

However, for point cloud scenarios my best advice is to simply omit the storage of edge indices and generate `k-NN` graphs using the power of CUDA and the newly released functions of [torch_cluster](https://rusty1s.github.io/pytorch_geometric/build/html/modules/nn.html#torch_geometric.nn.pool.knn_graph). For example, the [XConv operator](https://rusty1s.github.io/pytorch_geometric/build/html/modules/nn.html#torch_geometric.nn.conv.XConv) (which performs exceptionally btw), does not even take edge indices as input and instead creates them on the fly.
