### ISSUE TITLE
Implementation of Node2vec

### ISSUE THREAD

**Issue by EdisonLeeeee** [rusty1s/pytorch_geometric#957]
I think the implementation of node2vec is not exactly right (refer to [node2vec: Scalable Feature Learning for Networks](https://arxiv.org/abs/1607.00653)), the parameter `p` and `q`  are not always equal to 1.

From the source code of torch_cluster.random_walk, when `p!=1` and `q!=1`:
```python
if p != 1 or q != 1:  # pragma: no cover
        warnings.warn('Parameters `p` and `q` are not supported yet and will'
                      'be restored to their default values `p=1` and `q=1`.')
        p = q = 1
```

Instead, the implementation of node2vec is actually [Deepwalk](https://arxiv.org/abs/1403.6652) when p=q=1.

**Comment by rusty1s** [comment]
You are right that the current model resembles DeepWalk because we currently do not have implementations for `p!=1` and `q!=1`. That is why we warn the user when using different parameters. But this doesn't make the implementation wrong?

**Comment by EdisonLeeeee** [comment]
Hi, rusty1s,

I apologize for the misrepresentation, I just don't think  the implementation is exactly right since Node2vec is actually Deepwalk. Maybe you can rename the method (in `/examples`) to avoid any misuse?

Thanks for your excellent jobs, and I will keep an eye on your updates (especially the implementations for `p!=1` and `q!=1`).

**Comment by bwdeng20** [comment]
A `p,q` version random walking requires rewriting of  [batched random walk] (https://github.com/rusty1s/pytorch_cluster/blob/master/csrc/cpu/rw_cpu.cpp) implemented in `torch_cluster`, which is at present only for uniform random walk. Replacing it with a non-uniform version will incur more time consumption of choosing the next step since the possibilities to the neighbors are not even.

To tackle this problem, the authors of `node2vec` introduced `alias sampling`  into decision stage, which, however  needs a pre computing stage and much more space  and is not easy to integrate into present `node2vec` implementation in `PyG`.

**Comment by rusty1s** [comment]
This is now included in `torch-cluster==master` and will be pushed to an official release soon.
